export const temas = [
    { nombre: "arya-blue" },
    { nombre: "arya-green" },
    { nombre: "arya-orange" },
    { nombre: "arya-purple" },
    { nombre: "bootstrap4-light-blue" },
    { nombre: "bootstrap4-light-purple" },
    { nombre: "bootstrap4-dark-blue" },
    { nombre: "bootstrap4-dark-purple" },
    { nombre: "md-light-indigo" },
    { nombre: "md-light-deeppurple" },
    { nombre: "md-dark-indigo" },
    { nombre: "md-dark-deeppurple" },
    { nombre: "mdc-light-indigo" },
    { nombre: "mdc-light-deeppurple" },
    { nombre: "mdc-dark-indigo" },
    { nombre: "mdc-dark-deeppurple" },
    { nombre: "tailwind-light" },
    { nombre: "fluent-light" },
    { nombre: "lara-light-blue" },
    { nombre: "lara-light-indigo" },
    { nombre: "lara-light-purple" },
    { nombre: "lara-light-teal" },
    { nombre: "lara-dark-blue" },
    { nombre: "lara-dark-indigo" },
    { nombre: "lara-dark-purple" },
    { nombre: "lara-dark-teal" },
    { nombre: "soho-light" },
    { nombre: "soho-dark" },
    { nombre: "viva-light" },
    { nombre: "viva-dark" },
    { nombre: "mira" },
    { nombre: "nano" },
    { nombre: "saga-blue" },
    { nombre: "saga-green" },
    { nombre: "saga-orange" },
    { nombre: "saga-purple" },
    { nombre: "vela-blue" },
    { nombre: "vela-green" },
    { nombre: "vela-orange" },
    { nombre: "vela-purple" },


]